services:
  proteomics-wizard:
    image: ghcr.io/apactin/proteomics-wizard:latest
    ports:
      - "8525:8525"
    environment:
      - RUNS_DIR=/data/saved_runs
      - UNIPROT_CACHE_DIR=/data/uniprot_cache
    volumes:
      - ./data:/data
